### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by skruppy** [ChocolateLoverRaj/pam-any#1]
In order to package and distribute this library, please add a license.

**Comment by ChocolateLoverRaj** [comment]
Which one do you recommend?

**Comment by skruppy** [comment]
Looking at the dependencies, for now, all of them are licensed under the MIT license.
Most of them are dual licensed using Apache-2 license.

Looking at the linked dependencies of the compiled library on my system
```
ldd /usr/lib/security/pam_any.so 
	linux-vdso.so.1 (0x00007ffde5285000)
	libpam.so.0 => /usr/lib/libpam.so.0 (0x0000742368e78000)
	libpam_misc.so.0 => /usr/lib/libpam_misc.so.0 (0x0000742368e73000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000742368e4e000)
	libc.so.6 => /usr/lib/libc.so.6 (0x0000742368c6c000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x0000742368f38000)
	libaudit.so.1 => /usr/lib/libaudit.so.1 (0x0000742368c3f000)
	libcap-ng.so.0 => /usr/lib/libcap-ng.so.0 (0x0000742368c37000)
```
it seems like non of those limit your choosing of licenses.
Most of the libraries are using LGPL.

Other PAM modules, from the Linux PAM project itself, are [using](https://github.com/linux-pam/linux-pam/blob/master/COPYING) the BSD-3-Clause license and some version of GPL (required by Debian).

Combining all those information, you are quite free too choose a licence to your liking.
I personally would go with the Apache-2 license, since it has the neat feature in [section 5](https://www.apache.org/licenses/LICENSE-2.0) which clarifies the license of contributions and should prevent some claims from contributors.
